In [1]:
import pandas as pd
import numpy as np

import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_extraction import DictVectorizer
from sklearn.metrics import roc_auc_score
from sklearn.tree import export_text
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb

## 1. Data Preparation

In [5]:
data = 'https://github.com/alexeygrigorev/datasets/raw/refs/heads/master/jamb_exam_results.csv'

In [10]:
df = pd.read_csv(data)
df.head()

,JAMB_Score,Study_Hours_Per_Week,Attendance_Rate,Teacher_Quality,Distance_To_School,School_Type,School_Location,Extra_Tutorials,Access_To_Learning_Materials,Parent_Involvement,IT_Knowledge,Student_ID,Age,Gender,Socioeconomic_Status,Parent_Education_Level,Assignments_Completed
0,192,22,78,4,12.4,Public,Urban,Yes,Yes,High,Medium,1,17,Male,Low,Tertiary,2
1,207,14,88,4,2.7,Public,Rural,No,Yes,High,High,2,15,Male,High,NaN,1
2,182,29,87,2,9.6,Public,Rural,Yes,Yes,High,Medium,3,20,Female,High,Tertiary,2
3,210,29,99,2,2.6,Public,Urban,No,Yes,Medium,High,4,22,Female,Medium,Tertiary,1
4,199,12,98,3,8.8,Public,Urban,No,Yes,Medium,Medium,5,22,Female,Medium,Tertiary,1

In [14]:
# change the columns to lower case
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [16]:
df.head().T

                                     0       1         2         3         4
jamb_score                         192     207       182       210       199
study_hours_per_week                22      14        29        29        12
attendance_rate                     78      88        87        99        98
teacher_quality                      4       4         2         2         3
distance_to_school                12.4     2.7       9.6       2.6       8.8
school_type                     Public  Public    Public    Public    Public
school_location                  Urban   Rural     Rural     Urban     Urban
extra_tutorials                    Yes      No       Yes        No        No
access_to_learning_materials       Yes     Yes       Yes       Yes       Yes
parent_involvement                High    High      High    Medium    Medium
it_knowledge                    Medium    High    Medium      High    Medium
student_id                           1       2         3         4         5
age                                 17      15        20        22        22
gender                            Male    Male    Female    Female    Female
socioeconomic_status               Low    High      High    Medium    Medium
parent_education_level        Tertiary     NaN  Tertiary  Tertiary  Tertiary
assignments_completed                2       1         2         1         1

In [18]:
# remove student_id columns

del df['student_id']

In [20]:
# missing value
df.isnull().sum()

jamb_score                        0
study_hours_per_week              0
attendance_rate                   0
teacher_quality                   0
distance_to_school                0
school_type                       0
school_location                   0
extra_tutorials                   0
access_to_learning_materials      0
parent_involvement                0
it_knowledge                      0
age                               0
gender                            0
socioeconomic_status              0
parent_education_level          891
assignments_completed             0
dtype: int64

In [26]:
df.parent_education_level.value_counts(dropna=False)

parent_education_level
Secondary    1556
Primary      1335
Tertiary     1218
NaN           891
Name: count, dtype: int64

In [30]:
df.parent_education_level = df.parent_education_level.fillna(0)